export const ISO_CONTROLES = [
  { ref: "5.1",  dom: "Organizacional", nombre: "Políticas de seguridad de la información", desc: "Definir, aprobar y publicar políticas de seguridad de la información." },
  { ref: "5.2",  dom: "Organizacional", nombre: "Roles y responsabilidades de seguridad", desc: "Asignar y comunicar responsabilidades de seguridad de la información." },
  { ref: "5.3",  dom: "Organizacional", nombre: "Separación de funciones", desc: "Implementar separación de funciones para reducir el riesgo de fraude o error." },
  { ref: "5.4",  dom: "Organizacional", nombre: "Responsabilidades de la dirección", desc: "Asegurar que la dirección apoye activamente la seguridad de la información." },
  { ref: "5.5",  dom: "Organizacional", nombre: "Contacto con autoridades", desc: "Mantener contacto apropiado con autoridades relevantes." },
  { ref: "5.6",  dom: "Organizacional", nombre: "Contacto con grupos de interés especial", desc: "Mantener contacto con grupos de interés en seguridad de la información." },
  { ref: "5.7",  dom: "Organizacional", nombre: "Inteligencia sobre amenazas", desc: "Recopilar y analizar información sobre amenazas a la seguridad." },
  { ref: "5.8",  dom: "Organizacional", nombre: "Seguridad en gestión de proyectos", desc: "Integrar seguridad de la información en la gestión de proyectos." },
  { ref: "5.9",  dom: "Organizacional", nombre: "Inventario de información y activos", desc: "Identificar y mantener un inventario de activos de información." },
  { ref: "5.10", dom: "Organizacional", nombre: "Uso aceptable de información y activos", desc: "Definir y documentar reglas para el uso aceptable de activos." },
  { ref: "5.11", dom: "Organizacional", nombre: "Devolución de activos", desc: "Asegurar que los empleados devuelvan activos al finalizar su empleo." },
  { ref: "5.12", dom: "Organizacional", nombre: "Clasificación de información", desc: "Clasificar la información según su criticidad para la organización." },
  { ref: "5.13", dom: "Organizacional", nombre: "Etiquetado de información", desc: "Desarrollar e implementar procedimientos de etiquetado de información." },
  { ref: "5.14", dom: "Organizacional", nombre: "Transferencia de información", desc: "Controlar la transferencia de información dentro y fuera de la organización." },
  { ref: "5.15", dom: "Organizacional", nombre: "Control de acceso", desc: "Gestionar el acceso a la información y activos según necesidad de negocio." },
  { ref: "5.16", dom: "Organizacional", nombre: "Gestión de identidades", desc: "Gestionar el ciclo de vida completo de identidades digitales." },
  { ref: "5.17", dom: "Organizacional", nombre: "Información de autenticación", desc: "Controlar la asignación y gestión de credenciales de autenticación." },
  { ref: "5.18", dom: "Organizacional", nombre: "Derechos de acceso", desc: "Proveer, revisar, modificar y revocar derechos de acceso." },
  { ref: "5.19", dom: "Organizacional", nombre: "Seguridad en relaciones con proveedores", desc: "Implementar y monitorear acuerdos de seguridad con proveedores." },
  { ref: "5.20", dom: "Organizacional", nombre: "Acuerdos con proveedores", desc: "Establecer requisitos de seguridad en acuerdos con proveedores." },
  { ref: "5.21", dom: "Organizacional", nombre: "Cadena de suministro TIC", desc: "Gestionar riesgos de seguridad en la cadena de suministro TIC." },
  { ref: "5.22", dom: "Organizacional", nombre: "Seguimiento de servicios de proveedores", desc: "Monitorear, revisar y gestionar cambios en servicios de proveedores." },
  { ref: "5.23", dom: "Organizacional", nombre: "Seguridad en servicios en la nube", desc: "Establecer y gestionar seguridad en el uso de servicios cloud." },
  { ref: "5.24", dom: "Organizacional", nombre: "Planificación de gestión de incidentes", desc: "Planificar y preparar la gestión de incidentes de seguridad." },
  { ref: "5.25", dom: "Organizacional", nombre: "Evaluación de eventos de seguridad", desc: "Evaluar eventos de seguridad para determinar si constituyen incidentes." },
  { ref: "5.26", dom: "Organizacional", nombre: "Respuesta a incidentes de seguridad", desc: "Responder a incidentes según procedimientos documentados." },
  { ref: "5.27", dom: "Organizacional", nombre: "Aprendizaje de incidentes", desc: "Usar el conocimiento adquirido de incidentes para mejorar controles." },
  { ref: "5.28", dom: "Organizacional", nombre: "Recopilación de evidencias", desc: "Establecer procedimientos para identificar, recopilar y preservar evidencias." },
  { ref: "5.29", dom: "Organizacional", nombre: "Seguridad durante interrupciones", desc: "Planificar cómo mantener la seguridad durante interrupciones." },
  { ref: "5.30", dom: "Organizacional", nombre: "Preparación TIC para continuidad", desc: "Planificar, implementar y mantener la continuidad TIC." },
  { ref: "5.31", dom: "Organizacional", nombre: "Requisitos legales y contractuales", desc: "Identificar y cumplir requisitos legales, regulatorios y contractuales." },
  { ref: "5.32", dom: "Organizacional", nombre: "Derechos de propiedad intelectual", desc: "Proteger los derechos de propiedad intelectual de la organización." },
  { ref: "5.33", dom: "Organizacional", nombre: "Protección de registros", desc: "Proteger registros contra pérdida, destrucción o falsificación." },
  { ref: "5.34", dom: "Organizacional", nombre: "Privacidad y protección de datos", desc: "Garantizar privacidad y protección de datos personales según regulación." },
  { ref: "5.35", dom: "Organizacional", nombre: "Revisión independiente de seguridad", desc: "Revisar independientemente el enfoque de gestión de seguridad." },
  { ref: "5.36", dom: "Organizacional", nombre: "Cumplimiento de políticas de seguridad", desc: "Asegurar el cumplimiento de políticas y normas de seguridad." },
  { ref: "5.37", dom: "Organizacional", nombre: "Procedimientos de operación documentados", desc: "Documentar y mantener procedimientos para operaciones de seguridad." },
  { ref: "6.1",  dom: "Personas", nombre: "Cribado", desc: "Verificar antecedentes de candidatos antes de la contratación." },
  { ref: "6.2",  dom: "Personas", nombre: "Términos y condiciones del empleo", desc: "Incluir responsabilidades de seguridad en contratos de empleo." },
  { ref: "6.3",  dom: "Personas", nombre: "Concienciación, formación y capacitación", desc: "Proporcionar formación regular en seguridad de la información." },
  { ref: "6.4",  dom: "Personas", nombre: "Proceso disciplinario", desc: "Establecer proceso disciplinario formal para violaciones de seguridad." },
  { ref: "6.5",  dom: "Personas", nombre: "Responsabilidades al terminar empleo", desc: "Definir y cumplir responsabilidades de seguridad al finalizar el empleo." },
  { ref: "6.6",  dom: "Personas", nombre: "Acuerdos de confidencialidad", desc: "Formalizar acuerdos de confidencialidad o no divulgación." },
  { ref: "6.7",  dom: "Personas", nombre: "Trabajo remoto", desc: "Implementar controles para proteger información en trabajo remoto." },
  { ref: "6.8",  dom: "Personas", nombre: "Notificación de eventos de seguridad", desc: "Permitir al personal notificar eventos de seguridad observados." },
  { ref: "7.1",  dom: "Físico", nombre: "Perímetros de seguridad física", desc: "Definir y usar perímetros para proteger áreas de procesamiento." },
  { ref: "7.2",  dom: "Físico", nombre: "Controles de entrada física", desc: "Controlar el acceso físico a instalaciones seguras." },
  { ref: "7.3",  dom: "Físico", nombre: "Seguridad de oficinas e instalaciones", desc: "Diseñar y aplicar seguridad física en oficinas e instalaciones." },
  { ref: "7.4",  dom: "Físico", nombre: "Monitoreo de seguridad física", desc: "Monitorear continuamente las instalaciones para detectar intrusiones." },
  { ref: "7.5",  dom: "Físico", nombre: "Protección contra amenazas físicas", desc: "Diseñar protección contra desastres naturales y amenazas físicas." },
  { ref: "7.6",  dom: "Físico", nombre: "Trabajo en zonas seguras", desc: "Implementar medidas de seguridad para trabajar en zonas seguras." },
  { ref: "7.7",  dom: "Físico", nombre: "Puesto de trabajo despejado", desc: "Aplicar política de escritorio y pantalla limpios." },
  { ref: "7.8",  dom: "Físico", nombre: "Ubicación y protección del equipo", desc: "Ubicar y proteger el equipo para reducir riesgos ambientales." },
  { ref: "7.9",  dom: "Físico", nombre: "Activos fuera de instalaciones", desc: "Proteger activos fuera de las instalaciones de la organización." },
  { ref: "7.10", dom: "Físico", nombre: "Medios de almacenamiento", desc: "Gestionar medios de almacenamiento según clasificación y manejo." },
  { ref: "7.11", dom: "Físico", nombre: "Servicios de suministro", desc: "Proteger instalaciones de interrupciones por fallo de suministros." },
  { ref: "7.12", dom: "Físico", nombre: "Seguridad del cableado", desc: "Proteger cables de alimentación y telecomunicaciones." },
  { ref: "7.13", dom: "Físico", nombre: "Mantenimiento del equipo", desc: "Mantener correctamente el equipo para garantizar disponibilidad." },
  { ref: "7.14", dom: "Físico", nombre: "Eliminación o reutilización segura del equipo", desc: "Verificar que datos sensibles se eliminen antes de reutilizar equipos." },
  { ref: "8.1",  dom: "Tecnológico", nombre: "Dispositivos de punto final de usuario", desc: "Gestionar y proteger dispositivos de usuario final." },
  { ref: "8.2",  dom: "Tecnológico", nombre: "Derechos de acceso con privilegios", desc: "Restringir y gestionar el uso de derechos de acceso con privilegios." },
  { ref: "8.3",  dom: "Tecnológico", nombre: "Restricción de acceso a la información", desc: "Restringir el acceso a información según política de control de acceso." },
  { ref: "8.4",  dom: "Tecnológico", nombre: "Acceso al código fuente", desc: "Gestionar el acceso de lectura y escritura al código fuente." },
  { ref: "8.5",  dom: "Tecnológico", nombre: "Autenticación segura", desc: "Implementar mecanismos de autenticación segura incluyendo MFA." },
  { ref: "8.6",  dom: "Tecnológico", nombre: "Gestión de la capacidad", desc: "Monitorear y ajustar el uso de recursos para garantizar rendimiento." },
  { ref: "8.7",  dom: "Tecnológico", nombre: "Protección contra malware", desc: "Implementar controles de detección, prevención y recuperación ante malware." },
  { ref: "8.8",  dom: "Tecnológico", nombre: "Gestión de vulnerabilidades técnicas", desc: "Identificar, evaluar y remediar vulnerabilidades técnicas de forma oportuna." },
  { ref: "8.9",  dom: "Tecnológico", nombre: "Gestión de la configuración", desc: "Establecer, documentar y mantener configuraciones seguras." },
  { ref: "8.10", dom: "Tecnológico", nombre: "Eliminación de información", desc: "Eliminar información de forma segura cuando ya no sea necesaria." },
  { ref: "8.11", dom: "Tecnológico", nombre: "Enmascaramiento de datos", desc: "Enmascarar datos personales u otros datos sensibles." },
  { ref: "8.12", dom: "Tecnológico", nombre: "Prevención de fuga de datos", desc: "Detectar y prevenir la divulgación no autorizada de información sensible." },
  { ref: "8.13", dom: "Tecnológico", nombre: "Respaldo de información", desc: "Mantener copias de seguridad y verificar su restauración periódicamente." },
  { ref: "8.14", dom: "Tecnológico", nombre: "Redundancia de instalaciones de procesamiento", desc: "Implementar redundancia suficiente para cumplir requisitos de disponibilidad." },
  { ref: "8.15", dom: "Tecnológico", nombre: "Registro de actividades", desc: "Producir, almacenar, proteger y analizar registros de actividad." },
  { ref: "8.16", dom: "Tecnológico", nombre: "Actividades de monitoreo", desc: "Monitorear redes, sistemas y aplicaciones para detectar comportamientos anómalos." },
  { ref: "8.17", dom: "Tecnológico", nombre: "Sincronización de relojes", desc: "Sincronizar los relojes de sistemas con fuentes de tiempo autorizadas." },
  { ref: "8.18", dom: "Tecnológico", nombre: "Uso de programas de utilidad con privilegios", desc: "Controlar el uso de programas que puedan eludir controles del sistema." },
  { ref: "8.19", dom: "Tecnológico", nombre: "Instalación de software en producción", desc: "Gestionar e implementar procedimientos para instalar software en producción." },
  { ref: "8.20", dom: "Tecnológico", nombre: "Seguridad de redes", desc: "Gestionar y controlar la seguridad en redes para proteger sistemas." },
  { ref: "8.21", dom: "Tecnológico", nombre: "Seguridad de servicios de red", desc: "Identificar e implementar mecanismos de seguridad en servicios de red." },
  { ref: "8.22", dom: "Tecnológico", nombre: "Segregación de redes", desc: "Segregar grupos de servicios, usuarios y sistemas de información." },
  { ref: "8.23", dom: "Tecnológico", nombre: "Filtrado web", desc: "Gestionar el acceso a sitios web externos para reducir exposición a contenido malicioso." },
  { ref: "8.24", dom: "Tecnológico", nombre: "Uso de criptografía", desc: "Aplicar cifrado para proteger la confidencialidad e integridad de la información." },
  { ref: "8.25", dom: "Tecnológico", nombre: "Ciclo de vida de desarrollo seguro", desc: "Establecer reglas para el desarrollo seguro de software y sistemas." },
  { ref: "8.26", dom: "Tecnológico", nombre: "Requisitos de seguridad de aplicaciones", desc: "Identificar, especificar y aprobar requisitos de seguridad de aplicaciones." },
  { ref: "8.27", dom: "Tecnológico", nombre: "Principios de ingeniería de sistemas seguros", desc: "Establecer, documentar y aplicar principios de ingeniería segura." },
  { ref: "8.28", dom: "Tecnológico", nombre: "Codificación segura", desc: "Aplicar principios de codificación segura en el desarrollo de software." },
  { ref: "8.29", dom: "Tecnológico", nombre: "Pruebas de seguridad en desarrollo", desc: "Implementar procesos de pruebas de seguridad en el ciclo de desarrollo." },
  { ref: "8.30", dom: "Tecnológico", nombre: "Desarrollo externalizado", desc: "Supervisar y monitorear el desarrollo de software externalizado." },
  { ref: "8.31", dom: "Tecnológico", nombre: "Separación de entornos", desc: "Separar los entornos de desarrollo, prueba y producción." },
  { ref: "8.32", dom: "Tecnológico", nombre: "Gestión de cambios", desc: "Controlar cambios en instalaciones de procesamiento de información y sistemas." },
  { ref: "8.33", dom: "Tecnológico", nombre: "Información de prueba", desc: "Seleccionar, proteger y gestionar apropiadamente los datos de prueba." },
  { ref: "8.34", dom: "Tecnológico", nombre: "Protección de sistemas durante auditorías", desc: "Planificar y acordar pruebas de auditoría para minimizar interrupciones." },
];
